In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('../data/cleaned_data.csv')

df

C:\Users\honaa\AppData\Local\Temp\ipykernel_23512\3179130373.py:1: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/cleaned_data.csv')

,date,store_nbr,family,sales,onpromotion,holiday_type,locale,transferred,dcoilwtico,city,...,month,week,quarter,day_of_week,is_crisis,sales_lag_7,rolling_mean_7,is_weekend,is_holiday,promo_last_7_days
0,2013-01-01,1,AUTOMOTIVE,0.000,0,Holiday,National,False,93.14,Quito,...,1,1,1,Tuesday,0,0.000,0.000000,0,1,0.0
1,2013-01-01,1,BABY CARE,0.000,0,Holiday,National,False,93.14,Quito,...,1,1,1,Tuesday,0,0.000,0.000000,0,1,0.0
2,2013-01-01,1,BEAUTY,0.000,0,Holiday,National,False,93.14,Quito,...,1,1,1,Tuesday,0,0.000,0.000000,0,1,0.0
3,2013-01-01,1,BEVERAGES,0.000,0,Holiday,National,False,93.14,Quito,...,1,1,1,Tuesday,0,0.000,0.000000,0,1,0.0
4,2013-01-01,1,BOOKS,0.000,0,Holiday,National,False,93.14,Quito,...,1,1,1,Tuesday,0,0.000,0.000000,0,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3054343,2017-08-15,9,POULTRY,438.133,0,Holiday,Local,False,49.07,Quito,...,8,33,3,Tuesday,0,358.132,162.629143,0,1,13.0
3054344,2017-08-15,9,PREPARED FOODS,154.553,1,Holiday,Local,False,49.07,Quito,...,8,33,3,Tuesday,0,112.954,171.646286,0,1,10.0
3054345,2017-08-15,9,PRODUCE,2419.729,148,Holiday,Local,False,49.07,Quito,...,8,33,3,Tuesday,0,2299.715,362.564143,0,1,17.0
3054346,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8,Holiday,Local,False,49.07,Quito,...,8,33,3,Tuesday,0,170.000,341.282000,0,1,28.0
3054347,2017-08-15,9,SEAFOOD,16.000,0,Holiday,Local,False,49.07,Quito,...,8,33,3,Tuesday,0,15.678,280.139143,0,1,18.0

In [7]:

df['date'] = pd.to_datetime(df['date'])

df

,date,store_nbr,family,sales,onpromotion,holiday_type,locale,transferred,dcoilwtico,city,...,month,week,quarter,day_of_week,is_crisis,sales_lag_7,rolling_mean_7,is_weekend,is_holiday,promo_last_7_days
0,2013-01-01,1,AUTOMOTIVE,0.000,0,Holiday,National,False,93.14,Quito,...,1,1,1,Tuesday,0,0.000,0.000000,0,1,0.0
1,2013-01-01,1,BABY CARE,0.000,0,Holiday,National,False,93.14,Quito,...,1,1,1,Tuesday,0,0.000,0.000000,0,1,0.0
2,2013-01-01,1,BEAUTY,0.000,0,Holiday,National,False,93.14,Quito,...,1,1,1,Tuesday,0,0.000,0.000000,0,1,0.0
3,2013-01-01,1,BEVERAGES,0.000,0,Holiday,National,False,93.14,Quito,...,1,1,1,Tuesday,0,0.000,0.000000,0,1,0.0
4,2013-01-01,1,BOOKS,0.000,0,Holiday,National,False,93.14,Quito,...,1,1,1,Tuesday,0,0.000,0.000000,0,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3054343,2017-08-15,9,POULTRY,438.133,0,Holiday,Local,False,49.07,Quito,...,8,33,3,Tuesday,0,358.132,162.629143,0,1,13.0
3054344,2017-08-15,9,PREPARED FOODS,154.553,1,Holiday,Local,False,49.07,Quito,...,8,33,3,Tuesday,0,112.954,171.646286,0,1,10.0
3054345,2017-08-15,9,PRODUCE,2419.729,148,Holiday,Local,False,49.07,Quito,...,8,33,3,Tuesday,0,2299.715,362.564143,0,1,17.0
3054346,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8,Holiday,Local,False,49.07,Quito,...,8,33,3,Tuesday,0,170.000,341.282000,0,1,28.0
3054347,2017-08-15,9,SEAFOOD,16.000,0,Holiday,Local,False,49.07,Quito,...,8,33,3,Tuesday,0,15.678,280.139143,0,1,18.0

In [8]:
train_data = df[df['date'] < '2017-01-01']
test_data = df[df['date'] >= '2017-01-01']


print("Training data shape:", train_data.shape)
print("Test data shape:", test_data.shape)

Training data shape: (2642706, 25)
Test data shape: (411642, 25)